### ISSUE TITLE
fatal error: WebSocketsServer.h: No such file or directory   

### ISSUE THREAD

**Issue by karthidigi** [UncleGrumpy/Moonlight_8266#9]
Hi UncleGrumpy,

thank you very much for the detailed description. when i complied I am getting ```
fatal error: WebSocketsServer.h: No such file or directory | #include <WebSocketsServer.h>```

gcvt (Batt, 4, VCC) - this variable not declared in code.

Please help to resolve this errors.

**Comment by UncleGrumpy** [comment]
Thank you for your interest. I honestly have not looked at or tried to rebuild this code in several years. More than likely there need to be a few changes to be able to build with newer versions of the libraries and esp32-arduino core. I have not been using the esp8266 or the Arduino library for several years either, I've been using the newer esp32c3 and other esp32 models and the ESP-IDF.

I will try to find an esp8266 and update my Arduino libraries and see if I can fix this for you. Eventually I do plan on archiving this project and releasing a new version for ESP32 chips that will be written in Erlang and run on top of [AtomVM](https://github.com/atomvm/AtomVM).

**Comment by UncleGrumpy** [comment]
I have pushed a fix for the build error in #10. I also realized that I neglected to add library dependency info to the README. Thank you for pointing this out, I have updated the documentation to include info about the two libraries that this project depends on.  I also made it easier to re-enable console logging, I just had it all commented out, which is a pain to re-enable, so now there is a #def at the top of the code to enable log output for debugging. This issue should automatically close after I merge #10, but please feel free to open a new one if you run into trouble.

A word of warning, I have not tested this fix on hardware yet, but it should be fine. Thanks again, and please open a new issue of you discover any more problems.
